server:
  port: 9099
camunda:
  admin-user:
    id: demo
    password: demo
    email: ufo@andromeda.com
    first-name: Andromeda
    last-name: Galaxy
  bpm:
    database:
      type: postgres
    table-prefix: camunda.
    schema-update: true

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    #DB connection:
    url: jdbc:postgresql://localhost:5432/test?stringtype=unspecified
    username: postgres
    password: admin